#!/bin/sh

logfile='/var/log/autoupdates.log'

export DEBIAN_FRONTEND=noninteractive

log() {
  sudo tee -a "$logfile" 2>&1
}

checkreboot() {
  if [ -f /var/run/reboot-required ]; then
    echo "REBOOTING..." | sudo tee log
    sudo reboot
  fi
}

true | sudo tee "$logfile"

echo "UPDATE STARTED - $(date)" | log

checkreboot

sudo apt-get update 2>/dev/null

updates=$(apt list --upgradable | wc -l | awk '{$1=$1}1')

if [ $updates -gt 1 ]; then
  echo "$updates updates will be applied" | log
else
  echo "No updates available" | log
  (echo "UPDATE FINISHED - $(date)" | log) && exit 0
  exit 0
fi

sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade || (echo 'dist-upgrade error.' | log)

checkreboot

(echo "UPDATE FINISHED - $(date)" | log) && exit 0

