#!/bin/sh

logfile='/var/log/autoupdates.log'

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a
echo 'libc6 libraries/restart-without-asking boolean true' | debconf-set-selections

log() {
  sudo tee -a "$logfile" 2>&1
}

checkreboot() {
  if [ -f /var/run/reboot-required ]; then
    echo "REBOOTING..." | sudo tee log
    sudo reboot
  fi
}

true | sudo tee "$logfile"

echo "UPDATE STARTED - $(date)" | log

checkreboot

sudo apt-get update 2>/dev/null

updates=$(apt list --upgradable 2>/dev/null | wc -l | awk '{$1=$1}1')

if [ $updates -gt 1 ]; then
  echo "[i] $updates updates will be applied" | log
else
  echo "No updates available" | log
  (echo "UPDATE FINISHED - $(date)" | log) && exit 0
  exit 0
fi

echo "[i] executing autoremove..." | log
sudo apt-get -fuy --force-yes autoremove
checkreboot
echo "[i] executing clean..." | log
sudo apt-get --force-yes clean
checkreboot
echo "[i] executing upgrade..."
sudo apt-get ---force-yes -o Dpkg::Options::="--force-confdef" --force-yes -o Dpkg::Options::="--force-confold" -fuy upgrade || (echo 'dist-upgrade error.' | log)
checkreboot
echo "[i] executing dist-upgrade..."
sudo apt-get ---force-yes -o Dpkg::Options::="--force-confdef" --force-yes -o Dpkg::Options::="--force-confold" -fuy dist-upgrade || (echo 'dist-upgrade error.' | log)
checkreboot

(echo "UPDATE FINISHED - $(date)" | log) && exit 0

