#!/bin/sh

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

ctrl_c() {
  echo
  echo 'Caught Ctrl-C. Exiting...'
  exit 1
}

general_regex='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
exclusions='([2-9]{1}[5-9][6-9])|([3-9]{1}[0-9][0-9])|([2-9]{1}[6-9][0-9])'
ipv4regex='(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))'
ipv4cidrregex='(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))/[0-9]{1,2}'

grepfile() { grep -vE "${ipv4cidrregex}" "${@}" | grep -oE "${general_regex}" | grep -vE "${exclusions}" | grep -oE "${ipv4regex}"; }
grepit() { grep -vE "${ipv4cidrregex}" | grep -oE "${general_regex}" | grep -vE "${exclusions}" | grep -oE "${ipv4regex}"; }

# if arguments are passed:
if [ ! -z $1 ]; then
  for i in ${@}; do
    # if $i is a file:
    if [ -f "$i" ]; then
      grepfile "$i"
    else
      # if argument is input from stdin:
      echo "$i" | grepit
    fi
  done
else
  grepit
fi
